
  on:
    push:
      paths:
      - '.github/workflows/**'

  jobs:
    test:
      runs-on: ubuntu-latest
      steps:
      - name: Upload to CurseForge
        uses: itsmeow/curseforge-upload@v2
        id: upload_to_github
        with:
          token: ${{ secrets.CURSE_API_KEY }}
          project_id: 391708
          game_endpoint: minecraft
          file_path: Industrial Revolution - 0.1.1-ALPHA.jar
          changelog: Automatically upload JARS from github, added portuguese translation and drill recipes!
          display_name: Test Jar
          game_versions: minecraft-1-16:1.16.1:Java 14,Fabroc
          release_type: alpha